variables: ## These will get automatically populated in the future but for now they need to be manually configured
  SLU_IN_CLUSTER_ENDPOINT: "http://<name>.slu.svc.cluster.local/predict/hi/slu-latency-test-1/"
  APPLICATION_NAME: <name> # only use if your project has under scores in its name
  APPLICATION_NAMESPACE: slu # only use if your project has under scores in its name 
  APP_NAME: "skit-ai/slu/<name>" # only use if your project has under scores in its name

include:
  - project: 'skit-ai/infrastructure/ci-cd'
    ref: slu-updates
    file: '/templates/jobs/lint.yml'
  - project: 'skit-ai/infrastructure/ci-cd'
    ref: slu-updates
    file: '/templates/jobs/test.yml'
  - project: 'skit-ai/infrastructure/ci-cd'
    ref: slu-updates
    file: '/templates/jobs/quality.yml'
  - project: 'skit-ai/infrastructure/ci-cd'
    ref: slu-updates
    file: '/templates/jobs/tag.yml'
  - project: 'skit-ai/infrastructure/ci-cd'
    ref: slu-updates
    file: '/templates/jobs/build.yml'
  - project: 'skit-ai/infrastructure/ci-cd'
    ref: slu-updates
    file: '/templates/jobs/pre-release.yml'
  - project: 'skit-ai/infrastructure/ci-cd'
    ref: slu-updates
    file: '/templates/jobs/release.yml'
  - project: 'skit-ai/infrastructure/ci-cd'
    ref: slu-updates
    file: '/templates/slu-jobs/test.yml'

stages:
  - lint
  - test
  - quality
  - tag
  - build
  - pre-release
  - release
  - post-deploy

lint_python:
  allow_failure: true
  script:
    - pip3 install black
    - black .